name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Python 环境
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy pybind11 pytest

      # 构建项目
      - name: Build project
        run: |
          python setup.py build_ext --inplace

      # 运行测试
      - name: Run tests
        run: pytest test --maxfail=5 --disable-warnings